import { ClothingItem } from '@/context/WardrobeContext';

export const imageClothingItems: Omit<ClothingItem, 'id' | 'addedAt'>[] = [
  {
    name: 'Cobalt Blue Sneakers',
    category: 'Footwear',
    color: 'Blue',
    season: ['Spring', 'Summer', 'Fall'],
    image: '/images/01_Heroes_Cobalt_Flat.webp',
    brand: 'Nike',
    material: 'Synthetic',
    description: 'Stylish cobalt blue athletic sneakers',
    tags: ['athletic', 'casual', 'comfortable', 'sporty'],
    timesWorn: 0,
    topPairings: [],
    healthStatus: 'new',
    suggestedTags: ['running', 'everyday'],
    isPublic: false,
    isFavorite: false,
    price: 4500,
    costPerWear: 0
  },
  {
    name: 'Classic White Shirt',
    category: 'Tops',
    color: 'White',
    season: ['All Seasons'],
    image: '/images/11-5-2423211.webp',
    brand: 'Van Heusen',
    material: 'Cotton',
    description: 'Crisp white formal shirt',
    tags: ['formal', 'business', 'classic', 'versatile'],
    timesWorn: 0,
    topPairings: [],
    healthStatus: 'new',
    suggestedTags: ['office', 'professional'],
    isPublic: false,
    isFavorite: true,
    price: 2200,
    costPerWear: 0
  },
  {
    name: 'Black Formal Trousers',
    category: 'Bottoms',
    color: 'Black',
    season: ['All Seasons'],
    image: '/images/1764151687_8073584.avif',
    brand: 'Raymond',
    material: 'Wool Blend',
    description: 'Tailored black formal trousers',
    tags: ['formal', 'business', 'tailored', 'professional'],
    timesWorn: 0,
    topPairings: [],
    healthStatus: 'new',
    suggestedTags: ['office', 'meetings'],
    isPublic: false,
    isFavorite: false,
    price: 3500,
    costPerWear: 0
  },
  {
    name: 'Traditional Kurta',
    category: 'Tops',
    color: 'White',
    season: ['All Seasons'],
    image: '/images/241019_Ramraj_e-com11331_de46adea-1a7b-466d-93a5-c19e9708e17a.webp',
    brand: 'Ramraj Cotton',
    material: 'Cotton',
    description: 'Traditional white cotton kurta',
    tags: ['traditional', 'ethnic', 'comfortable', 'cultural'],
    timesWorn: 0,
    topPairings: [],
    healthStatus: 'new',
    suggestedTags: ['festival', 'casual'],
    isPublic: false,
    isFavorite: false,
    price: 1800,
    costPerWear: 0
  },
  {
    name: 'Casual Denim Jacket',
    category: 'Outerwear',
    color: 'Blue',
    season: ['Spring', 'Fall'],
    image: '/images/9923e3cff480d9bc180bffd3ed2d614a.jpg',
    brand: 'Levi\'s',
    material: 'Denim',
    description: 'Classic blue denim jacket',
    tags: ['casual', 'denim', 'layering', 'trendy'],
    timesWorn: 0,
    topPairings: [],
    healthStatus: 'new',
    suggestedTags: ['weekend', 'street-style'],
    isPublic: false,
    isFavorite: true,
    price: 4200,
    costPerWear: 0
  },
  {
    name: 'Brown Leather Shoes',
    category: 'Footwear',
    color: 'Brown',
    season: ['All Seasons'],
    image: '/images/a3441967fb2aedae.jpeg',
    brand: 'Clarks',
    material: 'Leather',
    description: 'Premium brown leather formal shoes',
    tags: ['formal', 'leather', 'professional', 'classic'],
    timesWorn: 0,
    topPairings: [],
    healthStatus: 'new',
    suggestedTags: ['office', 'business'],
    isPublic: false,
    isFavorite: false,
    price: 6500,
    costPerWear: 0
  },
  {
    name: 'Casual T-Shirt',
    category: 'Tops',
    color: 'Grey',
    season: ['Spring', 'Summer', 'Fall'],
    image: '/images/AndreasCollections-24166134877142218.jpg',
    brand: 'H&M',
    material: 'Cotton',
    description: 'Comfortable grey casual t-shirt',
    tags: ['casual', 'comfortable', 'everyday', 'basic'],
    timesWorn: 0,
    topPairings: [],
    healthStatus: 'new',
    suggestedTags: ['weekend', 'relaxed'],
    isPublic: false,
    isFavorite: false,
    price: 800,
    costPerWear: 0
  },
  {
    name: 'Smart Casual Blazer',
    category: 'Outerwear',
    color: 'Navy',
    season: ['All Seasons'],
    image: '/images/download.jpg',
    brand: 'Zara',
    material: 'Cotton Blend',
    description: 'Navy blue smart casual blazer',
    tags: ['smart-casual', 'blazer', 'professional', 'versatile'],
    timesWorn: 0,
    topPairings: [],
    healthStatus: 'new',
    suggestedTags: ['business-casual', 'meetings'],
    isPublic: false,
    isFavorite: true,
    price: 5500,
    costPerWear: 0
  },
  {
    name: 'Casual Chinos',
    category: 'Bottoms',
    color: 'Beige',
    season: ['Spring', 'Summer', 'Fall'],
    image: '/images/f20c4b328fb2df00c5c95053e61f6c5bcbe8b71c.avif',
    brand: 'Uniqlo',
    material: 'Cotton',
    description: 'Comfortable beige chino pants',
    tags: ['casual', 'chinos', 'comfortable', 'versatile'],
    timesWorn: 0,
    topPairings: [],
    healthStatus: 'new',
    suggestedTags: ['smart-casual', 'weekend'],
    isPublic: false,
    isFavorite: false,
    price: 2800,
    costPerWear: 0
  },
  {
    name: 'Polo Shirt',
    category: 'Tops',
    color: 'Blue',
    season: ['Spring', 'Summer'],
    image: '/images/images.jpg',
    brand: 'Ralph Lauren',
    material: 'Cotton Pique',
    description: 'Classic blue polo shirt',
    tags: ['polo', 'smart-casual', 'comfortable', 'classic'],
    timesWorn: 0,
    topPairings: [],
    healthStatus: 'new',
    suggestedTags: ['golf', 'casual-friday'],
    isPublic: false,
    isFavorite: false,
    price: 3200,
    costPerWear: 0
  },
  {
    name: 'Traditional Sherwani',
    category: 'Outerwear',
    color: 'Gold',
    season: ['All Seasons'],
    image: '/images/sherwani-for-men.webp',
    brand: 'Manyavar',
    material: 'Silk',
    description: 'Elegant gold silk sherwani',
    tags: ['traditional', 'formal', 'ethnic', 'wedding'],
    timesWorn: 0,
    topPairings: [],
    healthStatus: 'new',
    suggestedTags: ['wedding', 'festival'],
    isPublic: false,
    isFavorite: false,
    price: 12000,
    costPerWear: 0
  },
  {
    name: 'Casual Sneakers',
    category: 'Footwear',
    color: 'White',
    season: ['All Seasons'],
    image: '/images/shopping.webp',
    brand: 'Adidas',
    material: 'Synthetic',
    description: 'Clean white casual sneakers',
    tags: ['casual', 'sneakers', 'comfortable', 'everyday'],
    timesWorn: 0,
    topPairings: [],
    healthStatus: 'new',
    suggestedTags: ['street-style', 'weekend'],
    isPublic: false,
    isFavorite: true,
    price: 3800,
    costPerWear: 0
  }
];

export const matchingOutfits = [
  {
    name: 'Business Professional',
    items: ['Classic White Shirt', 'Black Formal Trousers', 'Brown Leather Shoes', 'Smart Casual Blazer'],
    season: ['All Seasons'],
    occasion: 'Work',
    favorite: false,
    description: 'Perfect for business meetings and formal occasions'
  },
  {
    name: 'Smart Casual Friday',
    items: ['Polo Shirt', 'Casual Chinos', 'Brown Leather Shoes'],
    season: ['Spring', 'Summer'],
    occasion: 'Work',
    favorite: true,
    description: 'Relaxed yet professional look for casual Fridays'
  },
  {
    name: 'Weekend Casual',
    items: ['Casual T-Shirt', 'Casual Chinos', 'Casual Sneakers', 'Casual Denim Jacket'],
    season: ['Spring', 'Fall'],
    occasion: 'Casual',
    favorite: false,
    description: 'Comfortable and stylish for weekend outings'
  },
  {
    name: 'Traditional Festive',
    items: ['Traditional Kurta', 'Traditional Sherwani'],
    season: ['All Seasons'],
    occasion: 'Special events',
    favorite: false,
    description: 'Traditional ethnic wear for festivals and cultural events'
  },
  {
    name: 'Athletic Casual',
    items: ['Casual T-Shirt', 'Casual Chinos', 'Cobalt Blue Sneakers'],
    season: ['Spring', 'Summer'],
    occasion: 'Casual',
    favorite: false,
    description: 'Sporty casual look for active days'
  }
];